pr:
  autoCancel: true

jobs:

- job: 'Linux'
  pool:
    vmImage: 'ubuntu-16.04'
  strategy:
    matrix:
      Python37:
        python.version: '3.7'
    maxParallel: 1

  steps:
  - bash: echo "##vso[task.prependpath]/usr/share/miniconda/bin"
    displayName: Add conda to PATH
  - bash: conda create -n foo -q --yes -c conda-forge -c bioconda htslib python gcc_impl_linux-64 binutils_impl_linux-64 binutils_linux-64 gcc_linux-64 libgcc-ng
    displayName: Installing dependencies
  - template: .azure-pipelines/test-template.yml

- job: 'OSX'
  pool:
    vmImage: 'macOS-10.13'
  strategy:
    matrix:
      Python37:
        python.version: '3.7'
    maxParallel: 1

  steps:
  - bash: echo "##vso[task.prependpath]$CONDA/bin"
    env: {
      ARCHS: "x86_64"
    }
    displayName: Add conda to PATH
  - bash: conda create -n foo -q --yes -c conda-forge -c bioconda htslib python clang clang_osx-64 clangxx
    displayName: Installing dependencies
  - template: .azure-pipelines/test-template.yml
